version: '3'

services:
  docker-DX-VEP:
    image: cccnrc/diagnosticator-vep:0.1
    # image: alpine-vep:0.0
    container_name: docker-DX-VEP
    volumes:
      - DX-UPLOAD:/home/VEP_INPUT
  docker-DX-ASILO:
    image: cccnrc/diagnosticator-asilo:0.1
    # image: asilo:0.0
    container_name: docker-DX-ASILO
    volumes:
      - DX-UPLOAD:/INPUT
#  docker-mysql:
#    image: mysql/mysql-server:latest
#    container_name: docker-mysql
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_DATABASE=diagnosticator
#      - MYSQL_USER=diagnosticator
#      - MYSQL_PASSWORD=diagnosticator
#    cap_add:
#      - SYS_NICE  # CAP_SYS_NICE
#    ports:
#      - '3307:3306'
#    volumes:
#      - mysqlDB:/var/lib/mysql
  docker-redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
  docker-diagnosticator:
    # build: .
    image: cccnrc/diagnosticator:0.8
    container_name: diagnosticator
    links:
#      - docker-mysql
      - docker-redis
    environment:
#      - DATABASE_URL=mysql+pymysql://diagnosticator:diagnosticator@docker-mysql:3306/diagnosticator
      - REDIS_URL=redis://docker-redis:6379
      - DEVELOPMENT_TESTING=1
      - UPLOAD_FOLDER=/home/diagnosticator/upload
      # - SERVER_ADDRESS=http://50.19.50.151:5000
    ports:
      - "9000:5000"
    expose:
      - '9000'
    restart: on-failure
#    depends_on:
#      - docker-mysql
    volumes:
      - DX-UPLOAD:/home/diagnosticator/upload
      - DX-DB:/home/diagnosticator/DB
  docker-rq-worker:
    # build: .
    image: cccnrc/diagnosticator:0.8
    container_name: rq-worker
    links:
#      - docker-mysql
      - docker-redis
    environment:
#      - DATABASE_URL=mysql+pymysql://diagnosticator:diagnosticator@docker-mysql:3306/diagnosticator
      - REDIS_URL=redis://docker-redis:6379/0
      - UPLOAD_FOLDER=/home/diagnosticator/upload
    entrypoint: venv/bin/rq
    command: worker -u redis://docker-redis:6379/0 diagnosticator-tasks
    volumes:
      - DX-UPLOAD:/home/diagnosticator/upload
      - DX-DB:/home/diagnosticator/DB

volumes:
#  mysqlDB:
  DX-UPLOAD:
  DX-DB:
